spring:

  # application-dev.yml
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret:
    key: